color0 #1d100d
color1 #ffb4ab
color2 #ffb4a2
color3 #ffb4a2
color4 #ffb94e
color5 #ffb4a2
color6 #ffb4a2
color7 #f7ddd7
color8 #a88a83
color9 #ffb4ab
color10 #ffb4a2
color11 #ffb4a2
color12 #ffb94e
color13 #ffb4a2
color14 #ffb4a2
color15 #f7ddd7

cursor                #f7ddd7
cursor_text_color     #1d100d
background            #1d100d
foreground            #f7ddd7
selection_foreground  #e1bfb7
selection_background  #59413b
active_border_color   #ffb4a2
inactive_border_color #59413b
url_color             #ffb4a2
