color0 #11131b
color1 #ffb4ab
color2 #b3c5ff
color3 #b3c5ff
color4 #f2afff
color5 #b3c5ff
color6 #b3c5ff
color7 #e1e2ed
color8 #8d90a0
color9 #ffb4ab
color10 #b3c5ff
color11 #b3c5ff
color12 #f2afff
color13 #b3c5ff
color14 #b3c5ff
color15 #e1e2ed

cursor                #e1e2ed
cursor_text_color     #11131b
background            #11131b
foreground            #e1e2ed
selection_foreground  #c3c6d7
selection_background  #434654
active_border_color   #b3c5ff
inactive_border_color #434654
url_color             #b3c5ff
